language: go
services: mongodb
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go install -race std
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/modocache/gory
  - export PATH=$GOPATH/bin:$PATH

script:
  - go test -race ./...
  - go test -cover ./...
  - ginkgo -r --randomizeAllSpecs -cover
notificaitons:
  email:
    recipients: garry.wright@me.com
    on_success: change
    on_failure: always
 