language: go
services: mongodb
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go install -race std
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/modocache/gory
  - go get github.com/onsi/ginkgo/ginkgo
  - go install github.com/mattn/goveralls
  - go install github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - go test -race ./...
  - go test -cover ./...
  - $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs -cover
  - go test -v -covermode=count -coverprofile=coverage.out $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
notificaitons:
  email:
    recipients: garry.wright@me.com
    on_success: change
    on_failure: always
 