language: go
services: mongodb
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go install -race std
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - go test -race ./...
  - go test -cover ./...
  - ginkgo -r --randomizeAllSpecs -cover
notificaitons:
  email:
    recipients: garry.wright@me.com
    on_success: change
    on_failure: always
 